apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.NAME}}-{{.Values.NAMESPACE_NAME}}-secrets
  namespace: {{.Values.NAMESPACE_NAME}}
data:
  DB_NAME: {{.Values.SECRETS.DB_NAME | b64enc }}
  DB_USER: {{.Values.SECRETS.DB_USER | b64enc}}
  DB_PASSWORD: {{.Values.SECRETS.DB_PASSWORD | b64enc}}
  DB_HOST: {{.Values.SECRETS.DB_HOST | b64enc}}
  DB_PORT: {{.Values.SECRETS.DB_PORT | toString | b64enc}}
  DB_SSLMODE: {{.Values.SECRETS.DB_SSLMODE | b64enc}}
  DB_TIMEZONE: {{.Values.SECRETS.DB_TIMEZONE | b64enc}}
  ADAREACH_URL: {{.Values.SECRETS.ADAREACH_URL | b64enc}}
  ADAREACH_USERNAME: {{.Values.SECRETS.ADAREACH_USERNAME | b64enc}}
  ADAREACH_PASSWORD: {{.Values.SECRETS.ADAREACH_PASSWORD | b64enc}}
type: Opaque