apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.NAME}}-{{.Values.NAMESPACE_NAME}}-secrets
  namespace: {{.Values.NAMESPACE_NAME}}
data:
  DB_NAME: {{.Values.SECRETS.DB_NAME}}
  DB_USER: {{.Values.SECRETS.DB_USER}}
  DB_PASSWORD: {{.Values.SECRETS.DB_PASSWORD}}
  DB_HOST: {{.Values.SECRETS.DB_HOST}}
  DB_PORT: {{.Values.SECRETS.DB_PORT}}
  DB_SSLMODE: {{.Values.SECRETS.DB_SSLMODE}}
  DB_TIMEZONE: {{.Values.SECRETS.DB_TIMEZONE}}
  ADAREACH_URL: {{.Values.SECRETS.ADAREACH_URL}}
  ADAREACH_USERNAME: {{.Values.SECRETS.ADAREACH_USERNAME}}
  ADAREACH_PASSWORD: {{.Values.SECRETS.ADAREACH_PASSWORD}}
type: Opaque