apiVersion: v1
kind: Service
metadata:
  name: {{.Values.NAME}}-{{.Values.NAMESPACE_NAME}}-svc
  namespace: {{.Values.NAME}}-{{.Values.NAMESPACE_NAME}}
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
      name: http-port
